---
- id: stylua
  name: StyLua (cargo)
  description: An opinionated Lua code formatter
  entry: stylua
  language: rust
  types:
    - lua

- id: stylua-system
  name: StyLua (system)
  description: An opinionated Lua code formatter
  entry: stylua
  language: system
  types:
    - lua

- id: stylua-release
  name: StyLua Release
  description: An opinionated Lua code formatter. Downloads Github release
  entry: stylua
  language: python
  types:
    - lua
